# Generated by Django 6.0.5 on 2026-05-28 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vehicle_alter_contact_vehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Scooter', 'Scooter'), ('Sport Bike', 'Sport Bike'), ('Premium Bike', 'Premium Bike')], max_length=50)),
                ('image', models.URLField()),
                ('images', models.JSONField(default=list)),
                ('emi', models.CharField(max_length=20)),
                ('emiValue', models.IntegerField()),
                ('downPayment', models.CharField(max_length=20)),
                ('downPaymentValue', models.IntegerField()),
                ('tenure', models.CharField(max_length=50)),
                ('maxTenure', models.IntegerField()),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('tagColor', models.CharField(blank=True, max_length=20, null=True)),
                ('priceText', models.CharField(max_length=20)),
                ('priceValue', models.IntegerField()),
                ('engineCC', models.CharField(max_length=50)),
                ('mileage', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('interestRate', models.FloatField(default=9.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.vehicle')),
            ],
        ),
    ]
