# Generated by Django 6.0.5 on 2026-06-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_vehicledetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing')], default='pending', max_length=20),
        ),
    ]
